version: "2"

services:
  pg:
    container_name: rs_pg
    restart: always
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - 5432

  application:
    build: .
    image: app
    links:
      - pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports:
      - 8901:80
    volumes:
      - ./data/:/app/data/